### PR TITLE
Use web test runner instead of karma

### PR DESCRIPTION
**Pull request by koddsson**
I also updated `simple-assert` to the latest version.

### CODE REVIEW

**Review by keithamus — APPROVED** [review]

**Comment by keithamus** [comment]
@koddsson looks like a genuine build error.

**Comment by koddsson** [comment]
> @koddsson looks like a genuine build error.

Whoops! I think I forgot to install Web Test Runner, and it worked on my machine because I have it installed globally.

**Comment by koddsson** [comment]
@keithamus There we go. What do you think about node 16 as a minimum node support?

**Comment by keithamus** [comment]
I’m very happy to push it up to node 16

**Pull request merged**
