### PR TITLE
Update MAINTAINERS

### PR DESCRIPTION
**Pull request by keithamus**

### CODE REVIEW

**Comment by keithamus** [comment]
@meeber for you 😄

**Comment by lucasfcosta** [comment]
LGTM :smile:

**Comment by lucasfcosta** [comment]
LGTM

Sidenote: Build is failing on IE.
I'll take a look at it as soon as I get home.

**Comment by meeber** [comment]
LGTM

**Comment by keithamus** [comment]
Merged despite failing build so we can get `LGTM` working 😄

**Pull request merged**
